### ISSUE TITLE
Please drop "Dedicated Marine OS" page

### ISSUE THREAD

**Issue by leamas** [opencpn-manuals/user#12]
We should IMHO limit the manual to stuff developed and maintained within the project. The "Marine OS" certainly isn't. On top of that, it is an extremely outdated, basidally a dead project based on Debian Jessie packages released 2015. Since OpenCPN has dropped support for Jessie since long, it is not possible to install a recent version OpenCPN on this platform.

So, please just drop the page.

While on it: Is it possible to re-organize the navigation tree so that "Ubuntu PPA" comes after "Linux installation overview" rather than before. Just to make the ordering somewhat sane...

@rgleason: for you,  as I understand it I lack permissions for structural changes like these (?)

**Comment by rgleason** [comment]
No you dont. But I will make the change in 2 hrs.

My back went bad so I cant sail. I am bummed. Otherwise i would be gone.

**Comment by rgleason** [comment]
> We should IMHO limit the manual to stuff developed and maintained within the project. The "Marine OS" certainly isn't. On top of that, it is an extremely outdated, basidally a dead project based on Debian Jessie packages released 2015. Since OpenCPN has dropped support for Jessie since long, it is not possible to install a recent version OpenCPN on this platform.

Alec,   this page has openplotter links on it.  That is an important subset.   However it is not Opencpn but uses O, so I have moved that page down to Supplementary Software and titled it Packaged OpenCPN, thus it can stay there and be out of date.
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:supplementary_software:opencpn-packages

BTW what I did to do this was make a new page where we wanted it by  adding in the url at the end  ":"  then "opencpn-packages"    Then hit enter.  Then go to edit and put in the title to reserve the page otherwise it will disappear when empty.

Then I went back to the Dedicated Marine OS page, went to Edit, copied all,  went to the new page, to Edit, and pasted and saved.  Looked at it and checked. 

Then to delete the Dedicated OS Page, select edit and then remove everything in the text and the page will disappear forever and we will not be able to get it back.

**Comment by rgleason** [comment]
> While on it: Is it possible to re-organize the navigation tree so that "Ubuntu PPA" comes after "Linux installation overview" rather than before. Just to make the ordering somewhat sane...

Yes, that is done by editing the  {{indexmenu_n>3}}  at the top of each page  I just switched the numbers.
and the titles in the index are taken from the first title in the document so they must be very short.

**Comment by rgleason** [comment]
Done
Do you want  Flatpak to be moved above  Ubuntu PPA?
Is this still active/current?

**Comment by leamas** [comment]
Flatpak is if not fine at least not worst. And the order now is just as it should, first the general page about Linux installations, and then more in depth in the the different ways.

The flatpak section has a lot of overlap, but we can live with it for now. Perhaps I bring my axe into those woods some day, who knows?

If you havn't read the new page Linux Installation Overview I suggest you do. I think it sorts things out (?).

**Comment by rgleason** [comment]
I will try to read it later. 

Is [Ubuntu PPA ](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:ubuntu_ppa)still viable and updated? 
I thought the change to tarballs for Plugins would make that less than perfect.

**Comment by leamas** [comment]
I certainly havn't checked the details. But the PPA is still the way to install a reasonable updated main OpenCPNpackage, even if it is not used for plugins any more.

**Comment by rgleason** [comment]
Ok thanks.  Closing
