### ISSUE TITLE
Flatpak Charts

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/user#13]
Don't we need a special page under Flatpak dealing with Charts and where they should be stored to have access to them?
https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:getting_started:opencpn_installation:flatpak

Also something about the change in where plugins are stored now?  (true for all platforms with updated PI)

**Comment by leamas** [comment]
> Don't we need a special page under Flatpak dealing with Charts and where they should be stored to have access to them?

I don't think so. Using something under  $HOME is the natural, default choice for any user. And we have the note in the Flatpak page, which describes both the issue and the solution

> Also something about the change in where plugins are stored now? (true for all platforms with updated PI)

Definitely not, this is not a user thing. The system is designed so that users don't have to know these locations.  Such details belongs in the Developer Manual.

Yes, I'm aware about the discussion about left stuff after uninstalling OpenCPN, the time these locations possibly needs to be handled by a user. If you can show me a single, user bug report about this I might re-consider my position. Until then, I basically thinks this is a non-issue.

**Comment by rgleason** [comment]
Alec I don't want to go there, sorry (:-))    going to close now.
